import Head from 'next/head'
import Image from 'next/image'
import { Caveat } from '@next/font/google'
import styles from '../styles/Home.module.css'
import hero from '../assets/hero.png'
import brush from '../assets/brush.png'

const caveat = Caveat({ weigth: ['500'], style: ['normal'], subsets: ['latin']})

const {ContentHero, 
  WrapperHero, 
  WrapperImage, 
  social, 
  ContentTextHero, 
  logo, 
  HeaderElement,
  ContextTextHeroTitle,
  BrushStyleHero,
  BrushStyle,
  OurArticles} = styles

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={WrapperHero}>
        <div className={WrapperImage}>
        <Image
            priority
            src={hero}
            alt="Hero image"
            layout="fill"
            objectFit="cover"
            placeholder="blur"
    
          />
        </div>
        <div className={ContentHero}>
          <div className={[HeaderElement, caveat.className].join(" ")}>
          <h1 className={logo}>
            Logo
          </h1>
          <ul className={social}>
            <li>
            Facebok
            </li>
            <li>
            Instagram
            </li>
            <li>
            YouTube
            </li>
          </ul>
          </div>
          
          <div className={[ContentTextHero, caveat.className].join(" ")}>
          <h2 className={ContextTextHeroTitle}>
            El secreto de tu cocina
          </h2>
          <Image
            className={BrushStyleHero}
            width={600}
            height={150}
            priority
            src={brush}
            alt="brush element"
          />
          </div>
          
        </div>
        
      </header>
      <main>
      <div className={[OurArticles, caveat.className].join(" ")}> 
          <h3 className={styles.Centerh3}>
            Nuestros artículos
          </h3>
          <Image
            className={BrushStyle}
            width={500}
            height={100}
            priority
            src={brush}
            alt="brush element"
            style={{ opacity: 0.20 }}
            
          />
        </div>
      </main>
    </>
  )
}
